app:
  name: quickstart
  dbms: mysql
  jeeServer: wildfly
#  singleHostName:  your-hostname
sharedDatabaseService:
  createDeployment: true
#  host: openshift.serv.run
#  port: 32432
#  databaseName: sampledb
#  username:
#  password:
operator:
  supportOpenshift: true
  env:
    #ENTANDO_DOCKER_REGISTRY_OVERRIDE: docker.io # Remove comment if you want to always use a specific docker registry
    #ENTANDO_DOCKER_IMAGE_ORG_OVERRIDE: entando # Remove the comment if you want to always use a specific docker organization
    ENTANDO_DEFAULT_ROUTING_SUFFIX: your.domain.com
    ENTANDO_POD_READINESS_TIMEOUT_SECONDS: "1000"
    ENTANDO_POD_COMPLETION_TIMEOUT_SECONDS: "1000"
    ENTANDO_DISABLE_KEYCLOAK_SSL_REQUIREMENT: "true"
    ENTANDO_K8S_OPERATOR_IMPOSE_DEFAULT_LIMITS: "false"
    ENTANDO_K8S_OPERATOR_FORCE_DB_PASSWORD_RESET: "true"
    ENTANDO_K8S_OPERATOR_DISABLE_PVC_GARBAGE_COLLECTION: "false"
    ENTANDO_K8S_OPERATOR_GC_CONTROLLER_PODS: "true"
    ENTANDO_ASSUME_EXTERNAL_HTTPS_PROVIDER: "false"
  tls:
# Create these secrets for TLS configuration
#    tlsSecretName: test-tls-secret
#    caCertSecretName: test-ca-cert-secret

deployPDA: false
