## specify your preferred DBMS. Valid values are embedded|mysql|postgresql. Please note that if you are using a sharedDatbase,
## this value cannot be 'embedded' as, by definition, as shared database cannot be embedded.
dbms: embedded
## To expose all the deployments for this app on a single hostname, uncomment the following line and provide the hostname
##singleHostName:  test.mycluster.com

##To share a single database service across all deployments, uncomment the following line and follow the subsequent instructions
#sharedDatabase:
##To deploy a single shared database container, uncomment the following line:
#  createDeployment: true
##Alternatively, to point to an existing external database, uncomment these lines, provide valid values to the properties
## and create a secret with the correct credentials (e.g. sample-secrets/sample-db-admin-credentials.yaml)
#  host: openshift.serv.run
#  port: 32432
#  databaseName: sampledb
#  dbAdminSecret: sample-db-admin-credentials
##Set this property to 'true' if you want to deploy the Entando Process Driven Apps plugin
deployPDA: false
