apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: entandodebundles.entando.org
spec:
  group: entando.org
  scope: Namespaced
  names:
    kind: EntandoDeBundle
    plural: entandodebundles
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                details:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                    dist-tags:
                      x-kubernetes-preserve-unknown-fields: true
                      type: object
                    versions:
                      description: >
                        The available versions for this bundle.
                      type: array
                      items:
                        type: string
                    keywords:
                      description: >
                        Keywords to associate with this bundle in the Entando Component Repository.
                      type: array
                      items:
                        type: string
                    thumbnail:
                      description: >
                        A base-64 encoded string for an image to display with the bundle in the Entando Component Repository.
                      type: string
                      maxLength: 320000
                tags:
                  description: >
                    The tags that are available for this bundle in the git repository hosting the bundle contents.
                  type: array
                  items:
                    type: object
                    properties:
                      version:
                        type: string
                      integrity:
                        type: string
                      shasum:
                        type: string
                      tarball:
                        type: string
            status:
              type: object
              properties:
                observedGeneration:
                  type: number
                entandoDeploymentPhase:
                  type: string
                serverStatuses:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
