apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: entandoapps.entando.org
spec:
  group: entando.org
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          jsonPath: .status.entandoDeploymentPhase
        - name: Observed Generation
          type: number
          jsonPath: .status.observedGeneration
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Host
          type: string
          jsonPath: .spec.ingressHostName
        - name: Image
          type: string
          jsonPath: .spec.image
        - name: DBMS
          type: string
          jsonPath: .spec.dbms
        - name: Replicas
          type: integer
          jsonPath: .spec.replicas
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  description: The number of pods that should participate in the cluster of this EntandoApp.
                  type: integer
                  minimum: 1
                  maximum: 10
                dbms:
                  description: >
                    The database management system (DBMS) to use for persistence of this EntandoApp. 
                    Can be any of mysql, oracle  postgresql, embedded or none. Only 1 replica of the container is supported if embedded is selected. If Oracle is selected it must be created manually, the operator does not deploy Oracle instances.

                    See [here] (https://dev.entando.org/v6.3/docs/concepts/operator-intro.html#database-deployment) for how the operator will create and configure the DBMS.
                  type: string
                  pattern: '^(mysql|oracle|postgresql|embedded|none)$'
                storageClass:
                  description: >
                    The name of the StorageClass to use for PersistentVolumeClaims created for this EntandoApp
                  type: string
                ingressHostName:
                  description: >
                    The hostname that will be used to access this EntandoApp from outside the cluster. The Entando
                    Operator will create an Ingress reflecting this hostname, and expose this EntandoApp on the
                    path specified in 'EntandoApp.spec.ingressPath' on
                    this host. If omitted, the Entando Operator will automatically generate a hostname.

                    See [here] (https://dev.entando.org/v6.3/docs/concepts/operator-intro.html#ingress-path-generation) for how the operator will create and configure the Ingress.
                  type: string
                  pattern: '^([A-Za-z0-9-]{1,63}\.)*[[A-Za-z0-9-]{1,63}$'
                ingressPath:
                  description: >
                    The path that will be used to expose this EntandoApp on the ingress host
                    specified in 'EntandoApp.spec.ingressHostname'. This property needs to be in sync with
                    the web context path that is used in the underlying WAR deployment. It should either be
                    the name of the WAR file that gets generated, or it needs to be in sync with the web context
                    specified in the jboss-web.xml deployment descriptor. The default value is 'entando-de-app'.
                  type: string
                tlsSecretName:
                  description: >
                    The name of a standard Kubernetes TLS Secret, assumed to be in the same Namespace as the EntandoApp being created.
                    See [here](https://dev.entando.org/v6.3/docs/concepts/operator-intro.html#tls-secret-creation) for details and instructions on
                    creating a secret for your Entando applications.
                  type: string
                  pattern: '^([a-z])+([a-z0-9-\.])*[a-z0-9]$'
                serviceAccountToUse:
                  description: >
                    The Kubernetes ServiceAccount in the Namespace of the EntandoApp that is to be used for
                    the Pods hosting the EntandoApps. The default is 'default'.
                  type: string
                  pattern: '^([a-z])+([a-z0-9-\.])*[a-z0-9]$'
                environmentVariables:
                  description: >
                    A list of environment variable following the standard structure of Kubernetes Environment Variables
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                      valueFrom:
                        type: object
                        properties:
                          configMapKeyRef:
                            type: object
                            properties:
                              name:
                                description: Name of a ConfigMap in the same namespace as the EntandoApp
                                type: string
                              key:
                                description: Key of the ConfigMap entry in that holds the value to be used for the EnvironmentVariable
                                type: string
                          fieldRef:
                            type: object
                            properties:
                              apiVersion:
                                description: Version of the API to used for the field expression
                                type: string
                              fieldPath:
                                description: Full expression starting from the Pod resource
                                type: string
                          resourceFieldRef:
                            type: object
                            properties:
                              containerName:
                                description: Name of the container to use
                                type: string
                              resource:
                                description: Name of the resource to use
                                type: string
                          secretKeyRef:
                            type: object
                            properties:
                              name:
                                description: Name of a Secret in the same namespace as the EntandoApp
                                type: string
                              key:
                                description: Key of the Secret entry in that holds the value to be used for the EnvironmentVariable
                                type: string
                resourceRequirements:
                  description: >
                    The projected resource requirements of the given EntandoApp deployment. Specifies the limits that the
                    container is expected to respect, and the size of requests that will be initiated on behalf of the
                    container. When omitted our known defaults will be applied.
                  type: object
                  properties:
                    storageRequest:
                      description: >
                        Size of persistent storage that will be requested when deployed. Can be omitted. Supported only
                        by a small subset of Kubernetes storage providers.
                      type: string
                    storageLimit:
                      description: >
                        The maximum amount of persistent storage require by the EntandoApp. Mainly used
                        when the 'embedded' DBMS option is used. Limits and requests for memory are measured in bytes. You can
                        express storage as a plain integer using one of these suffixes: T, G, M, K. You can also
                        use the power-of-two equivalents: Ti, Gi, Mi, Ki.
                      type: string
                    memoryRequest:
                      description: >
                        The amount of memory that will be requested when deployed. A pod will only be deployed to a node
                        that has this amount of memory available. You can  express memory as a plain integer using one of
                        these suffixes: T, G, M, K. You can also use the power-of-two equivalents: Ti, Gi, Mi, Ki.
                      type: string
                    memoryLimit:
                      description: >
                        The maximum amount of memory that the container is expected to use. Kubernetes will limit the amount
                        of memory to the container the to amount specified. You can  express memory as a plain integer using one of
                        these suffixes: T, G, M, K. You can also use the power-of-two equivalents: Ti, Gi, Mi, Ki.
                      type: string
                    cpuRequest:
                      description: >
                        The amount of CPU units that will be requested from a node at deployment time. A pod will only be
                        deployed to a node if the node has this amount of CPU units available. Supports decimal numbers, or
                        alternatively the suffix 'm' can be used to specify a millicore. Precision lower than 1m is not supported.
                      type: string
                    cpuLimit:
                      description: >
                        The maximum amount of CPU units that will be required by the container.Supports decimal numbers, or
                        alternatively the suffix 'm' can be used to specify a millicore. Precision lower than 1m is not supported.
                      type: string
                    fileUploadLimit:
                      description: >
                        The maximum file upload size. This limit will be enforced by NGINX compliant Ingress controllers.
                        The suffix 'm' allows the limit to be specified in megabytes, eg. '120m'.
                      type: string
                keycloakToUse:
                  type: object
                  description: >
                    The properties of this object configure which Keycloak server this EntandoApp will be using,
                    and allows the user to override the default Realm and PublicClientID to use.
                  properties:
                    realm:
                      description: >
                        The realm that will be used to create the OIDC Client for this EntandoApp. If omitted, the
                        default realm will be 'Entando'. If another realm is specified, and it doesn't exist by
                        the time the EntandoApp is deployed, the realm will be created on demand.
                      type: string
                    publicClientId:
                      description: >
                        The Client ID for the Public client that will be created this EntandoApp.
                        Only required if this microservice should be accessible from outside the cluster. The
                        default is 'entando-web'.
                      type: string
                    name:
                      description: >
                        The name of the EntandoKeycloakServer to use as OIDC provider. If no name is provided, the
                        Entando Operator will then look for any EntandoKeycloakServer in the same Namespace as this
                        EntandoApp and use it as OIDC provider. If no EntandoKeycloakServer is found,
                        it will then use the (last) EntandoKeycloakServer that was marked as the cluster wide  default
                        using the property EntandoKeycloakServer.spec.isDefault.
                      type: string
                    namespace:
                      description: >
                        The Namespace of the EntandoKeycloakServer to use as OIDC provider. This value is only
                        evaluated if the 'spec.keycloakToUse.name' property has been set on this
                        EntandoClusterInfrastructure.  If no Namespace is provided,
                        but a name was provided, the Entando Operator will then look for the
                        EntandoKeycloakServer with the name specified in the same Namespace as this
                        EntandoApp and use it as OIDC provider.
                      type: string
                clusterInfrastructureToUse:
                  type: object
                  description: >
                    The properties of this object configure which Entando K8S Service will be used.
                  properties:
                    name:
                      description: >
                        The name of the EntandoClusterInfrastructure to use as Entando K8S Service. If no name is provided, the
                        Entando Operator will then look for any EntandoClusterInfrastructure in the same Namespace as this
                        EntandoApp and use it. If no EntandoClusterInfrastructure is found,
                        it will then use the (last) EntandoClusterInfrastructure that was marked as the cluster wide  default
                        using the property EntandoClusterInfrastructure.spec.isDefault.
                      type: string
                    namespace:
                      description: >
                        The Namespace of the EntandoClusterInfrastructure to use. This value is only
                        evaluated if the 'spec.clusterInfrastructureToUse.name' property has been set on this
                        EntandoApp. If no Namespace is provided,
                        but a name was provided, the Entando Operator will then look for the
                        EntandoClusterInfrastructure with the name specified in the same Namespace as this
                        EntandoApp and use it.
                      type: string
                standardServerImage:
                  description: >
                    Specifies the standard server base image that this EntandoApp has been packaged in. Valid values
                    are wildfly (https://github.com/entando/entando-docker-base-images/tree/master/entando-wildfly17-base)
                    or eap (https://github.com/entando/entando-docker-base-images/tree/master/entando-eap72-clustered-base).
                    This property is required to provide the appropriate environment variables to the deployed container.
                    This should be used in conjunction with the 'EntandoApp.spec.customServerImage' property to indicate
                    which base image the custom server image was based on. If no customer server image is specified, this
                    property will result in the deployment of the entando/entando-de-app-eap image for the value 'eap',
                    and the entando/entando-de-app-wildfly image for the value 'wildfly'.
                  type: string
                  pattern: '^(wildfly|eap)$'
                customServerImage:
                  description: >
                    The full Docker image URI for the Docker image to be deployed. This is only required in scenarios
                    where the user has created an independent Maven project based on the entando-de-app project
                    (https://github.com/entando-k8s/entando-de-app) and packaged this project to its own image.
                    Use this property in conjunction with 'EntandoApp.spec.standardServerImage' to ensure that the
                    Entando Operator provides it with the correct environment variables.
                  type: string
                ecrGitSshSecretName:
                  description: >
                    A standard Kubernetes Secret that contains an SSH private/public keypair to use to access the
                    Entando Bundles on the Git server they are hosted on.
                  type: string
                  pattern: '^([a-z])+([a-z0-9-\.])*[a-z0-9]$'
                backupGitSpec:
                  description: >
                    Use this object to configure the git repository that this EntandoApp will be backed up to or backed
                    up from. This functionality is not available yet. Please ignore.
                  type: object
                  properties:
                    backupGitRepo:
                      description: >
                        The full URL of the backup git repository
                      type: string
                    backupGitSecretName:
                      description: >
                        The name of a standard Kubernetes Secret that contains a single field 'token' that will be
                        used for authentication when backing up or restoring backups from Git.
                      type: string
                    backupResponsibility:
                      description: >
                        One of 'backup' or 'restore'
                      type: string
                      pattern: '^(backup|restore)$'
            status:
              type: object
              properties:
                observedGeneration:
                  type: number
                entandoDeploymentPhase:
                  type: string
                serverStatuses:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
  names:
    kind: EntandoApp
    plural: entandoapps
    shortNames:
      - enap
  scope: Namespaced
