{{- if .Values.sharedDatabaseService }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}-db-admin-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username:  "{{ .Values.sharedDatabaseService.username }}"
  password: "{{ .Values.sharedDatabaseService.password }}"
{{- end }}
