apiVersion: "entando.org/v1"
kind: "EntandoClusterInfrastructure"
metadata:
  name: "{{ .Release.Name }}-eci"
  annotations:
    entando.org/processing-instruction: defer
spec:
{{- if .Values.singleHostname }}
  ingressHostName: {{ .Values.singleHostname }}
{{- end}}
  replicas: 1
  isDefault: true
