kind: "EntandoKeycloakServer"
apiVersion: "entando.org/v1"
metadata:
  name: "{{ .Release.Name }}-kc"
  annotations:
    entando.org/processing-instruction: defer
spec:
  dbms: {{ .Values.dbms }}
{{- if .Values.singleHostname }}
  ingressHostName: {{ .Values.singleHostname }}
{{- end}}
  isDefault: true
  replicas: 1
