kind: "EntandoCompositeApp"
apiVersion: "entando.org/v1"
metadata:
  name: "{{ .Values.app.name }}-composite-app"
  namespace: "{{ .Release.Namespace }}"
entandoStatus:
  serverStatuses: {}
  entandoDeploymentPhase: "requested"
spec:
  components:
{{- if .Values.sharedDatabase }}
    - kind: "EntandoCustomResourceReference"
      metadata:
        name: "database-service"
      spec:
        targetKind: "EntandoDatabaseService"
        targetName: "{{ .Values.app.name }}-ds"
{{- end }}
    - kind: "EntandoCustomResourceReference"
      metadata:
        name: "keycloak-server"
      spec:
        targetKind: "EntandoKeycloakServer"
        targetName: "{{ .Values.app.name }}-kc"
    - kind: "EntandoCustomResourceReference"
      metadata:
        name: "{{ .Values.app.name }}-eci"
      spec:
        targetKind: "EntandoClusterInfrastructure"
        targetName: "{{ .Values.app.name }}-eci"
    - kind: "EntandoCustomResourceReference"
      metadata:
        name: "app"
      spec:
        targetKind: "EntandoApp"
        targetName: "{{ .Values.app.name }}"
{{- if .Values.deployPDA }}
    - kind: "EntandoCustomResourceReference"
      metadata:
        name: "{{ .Values.app.name }}-pda"
      spec:
        targetKind: "EntandoPlugin"
        targetName: "{{ .Values.app.name }}-pda"
    - kind: "EntandoCustomResourceReference"
      metadata:
        name: "{{ .Values.app.name }}-pda"
      spec:
        targetKind: "EntandoAppPluginLink"
        targetName: "{{ .Values.app.name }}-pda-apl"
{{- end }}
