kind: "EntandoCompositeApp"
apiVersion: "entando.org/v1"
metadata:
  name: "{{ .Release.Name }}-composite-app"
spec:
  components:
{{- if .Values.sharedDatabase }}
    - kind: "EntandoCustomResourceReference"
      metadata:
        name: "database-service"
      spec:
        targetKind: "EntandoDatabaseService"
        targetName: "{{ .Release.Name }}-ds"
{{- end }}
    - kind: "EntandoCustomResourceReference"
      metadata:
        name: "keycloak-server"
      spec:
        targetKind: "EntandoKeycloakServer"
        targetName: "{{ .Release.Name }}-kc"
    - kind: "EntandoCustomResourceReference"
      metadata:
        name: "{{ .Release.Name }}-eci"
      spec:
        targetKind: "EntandoClusterInfrastructure"
        targetName: "{{ .Release.Name }}-eci"
    - kind: "EntandoCustomResourceReference"
      metadata:
        name: "app"
      spec:
        targetKind: "EntandoApp"
        targetName: "{{ .Release.Name }}"
{{- if .Values.deployPDA }}
    - kind: "EntandoCustomResourceReference"
      metadata:
        name: "{{ .Release.Name }}-pda"
      spec:
        targetKind: "EntandoPlugin"
        targetName: "{{ .Release.Name }}-pda"
    - kind: "EntandoCustomResourceReference"
      metadata:
        name: "{{ .Release.Name }}-pda"
      spec:
        targetKind: "EntandoAppPluginLink"
        targetName: "{{ .Release.Name }}-pda-apl"
{{- end }}
