{{- if .Values.deployPDA }}
kind: "EntandoAppPluginLink"
apiVersion: "entando.org/v1"
metadata:
  name: "{{ .Values.app.name }}-pda-apl"
  annotations:
    entando.org/processing-instruction: defer
spec:
  entandoAppName: "{{ .Values.app.name }}"
  entandoPluginName: "{{ .Values.app.name }}-pda"
{{- end }}