{{- if .Values.sharedDatabase }}
kind: "EntandoDatabaseService"
apiVersion: "entando.org/v1"
metadata:
  name: "{{ .Release.Name }}-ds"
  annotations:
    entando.org/processing-instruction: defer
spec:
  dbms: {{ .Values.dbms }}
  {{- if .Values.sharedDatabase.createDeployment }}
  createDeployment: true
  {{- else }}
  databaseName: "{{ .Values.sharedDatabase.databaseName }}"
  host: "{{ .Values.sharedDatabase.host }}"
  port: "{{ .Values.sharedDatabase.port }}"
  secretName: "{{ .Values.sharedDatabase.dbAdminSecret }}"
  {{- end }}
{{- end }}
